### ISSUE TITLE
Packer fails

### ISSUE THREAD

**Issue by clumbo** [kencx/homelab#2]
Packer fails with the following error

`==> proxmox-clone.base: Creating ephemeral key pair for SSH communicator...
==> proxmox-clone.base: Created ephemeral SSH key pair for communicator
==> proxmox-clone.base: Creating VM
==> proxmox-clone.base: Error creating VM: vm 'debian11-cloud' not found
Build 'proxmox-clone.base' errored after 62 milliseconds 44 microseconds: Error creating VM: vm 'debian11-cloud' not found`

However the packer variables require `iso_url` and `iso_checksum` but don't seem to be used?

its presuming an already created VM called debian-cloud is provisioned?

**Comment by kencx** [comment]
You're right, the `proxmox-clone` builder expects an existing VM template to clone, which I added manually. The `iso_*` variables were added preemptively because I planned on trying out the `proxmox-iso` builder but never got around to it yet.

Apologies for the confusion, I'm always changing (and breaking) stuff and some of the configuration is tailored to my setup so I would caution on running the repo as is directly. It would be better to use as an example or base and customize it for your own setup.

**Comment by kencx** [comment]
I've updated the Packer builder to v1.1.2, added some configurable variables and made the docs clearer (for `proxmox-clone`) so I hope that helps clear things up. The `proxmox-iso` builder is still WIP though.

**Comment by clumbo** [comment]
Thanks for replying and helping out, I understand you are hosting this publicly to help people out and much appreciated, I just thought I would mention the problem to help out while I get something similar running 

Thanks for making this public it helps an enormous amount.

**Comment by kencx** [comment]
No worries, I'm glad you are finding this useful!
